name: Build and publish PHAR on release

on:
  release:
    types: [ created ]

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-progress

      - name: Install box.phar
        run: curl -Lo bin/box.phar https://github.com/box-project/box/releases/latest/download/box.phar

      - name: Build PHAR
        run: composer build-phar

      - name: Upload PHAR
        uses: actions/upload-artifact@v2
        with:
          name: build-regexp.phar
          path: bin/build-regexp.phar

  publish-phar:
    runs-on: ubuntu-latest
    needs:
      - build-phar

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-regexp.phar
          path: .

      - name: Upload box.phar
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build-regexp.phar
